[package]
name = "scorch/scorch-rblx"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
Knit = "sleitnick/knit@1.6.0"
Trove = "sleitnick/trove@1.1.0"
Timer = "sleitnick/timer@1.1.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
